### ISSUE TITLE
Render Palette

### ISSUE THREAD

**Issue by aschaeffer** [aschaeffer/reactive-graph-flow-editor#1]
### Goal

On the left side, a palette is rendered

### Tasks

- [ ] Model Palette Group
- [ ] Model Palette Item
- [ ] Get a list of namespaces from the GraphQL endpoint and store palette groups
- [ ] Get a list of entity types from the GraphQL endpoint and store palette items
- [ ] Render Palette Groups as accordions
- [ ] Render Palette Item Icon
- [ ] Render Palette Item Text
- [ ] Render Palette Item Tooltip
- [ ] On click on Palette Item: TODO
