### ISSUE TITLE
System Tray

### ISSUE THREAD

**Issue by aschaeffer** [aschaeffer/reactive-graph-flow-editor#10]
### Goal

The user can toggle the visibility state of the application and quit the application via the system tray.

### Tasks

- [x] Implement tray menu in tauri
  - [x] Toggle → The tauri application gets minimized to tray
  - [x] Quit → The tauri application shuts down
