### ISSUE TITLE
Extend plugin panel with local build capabilities

### ISSUE THREAD

**Issue by aschaeffer** [aschaeffer/reactive-graph-flow-editor#12]
### Tasks

- [ ] Add a dialog to add a plugin repository
- [ ] Add a dialog to add a plugin within a plugin repository
- [ ] Add a button to update and deploy the plugin from the plugin repository
- [ ] Use GraphQL endpoint: https://github.com/inexorgame/inexor-rgf-application/issues/72
