### ISSUE TITLE
Selection of flow types and flow instances

### ISSUE THREAD

**Issue by aschaeffer** [aschaeffer/reactive-graph-flow-editor#15]
### Goal

Store the currently selected flow type and flow instance. You can only select both

### Tasks

- [ ] Create a store which contains
  - [ ] The flow type
  - [ ] AND the flow instance
- [ ] `select(flowInstanceUuid)`
  * Selects the given flow instance and selects its flow type
- [ ] `unselect()`
  * Removes both selections
- [ ] `getFlowInstances(namespace, flowTypeName) -> List<Uuid>`
  * DropDown for creating a flow instance for a flow type
- [ ] `createNewFlowInstance(namespace, flowTypeName)`
  * Creates a new flow instance from an existing flow type
- [ ] `createNewFlowType(namespace, flowTypeName, namespace entityTypeName)`
  * Creates an empty flow type from an existing entity type
- [ ] Show two DropDowns in two columns (50%/50%) above the flow editor: one with the selected flow type and one with the selected flow instance
- [ ] Handle update of the flow instance drop down
- [ ] Add button to create a flow instance from the flow type
- [ ] Add button to create a new flow type → Open `Create Flow Type Modal Dialog`
- [ ] Handle update of the flow type drop down → Open `Create Flow Instance Modal Dialog`
- [ ] Add button to delete the currently selected flow instance

### Non-Goals

- No visual representation in the editor yet
