### ISSUE TITLE
Status Line

### ISSUE THREAD

**Issue by aschaeffer** [aschaeffer/reactive-graph-flow-editor#5]
### Goal

On the very bottom, a status line is shown.

### Tasks

- [ ] Server name info
  - [ ] On click open the server selection modal
- [x] Components count
- [x] Entity types count
- [x] Relation types count
- [x] Flow types count
- [ ] Total entity instance count
- [ ] Entity instance count (currently selected flow)
- [ ] Relation instance count (currently selected flow)
- [ ] Flow instance count
- [ ] Status message
