### ISSUE TITLE
Main Menu

### ISSUE THREAD

**Issue by aschaeffer** [aschaeffer/reactive-graph-flow-editor#6]
### Goal

The main menu is shown when the user clicks on the burger menu icon.

### Tasks

- [x] Link to Settings Modal
- [x] Link to About Modal
- [x] Link to Plugins Modal
- [x] Link to Servers Modal
- [x] Quit → Exit the application
