### ISSUE TITLE
Modal About

### ISSUE THREAD

**Issue by aschaeffer** [aschaeffer/reactive-graph-flow-editor#7]
### Goal

Information about the flow editor is shown in a modal.

### Tasks

- [x] Show version of the flow editor
- [x] Show rust compiler version
- [x] Show build date
- [x] Show the licence
- [x] Show logo
- [x] Show credits
