### ISSUE TITLE
Panel Plugins

### ISSUE THREAD

**Issue by aschaeffer** [aschaeffer/reactive-graph-flow-editor#8]
### Goal

The modal shows a list of plugins and let the user activate/deactivate the plugins.

### Tasks

- [x] Store
  - [x] Load plugins from GraphQL endpoint
  - [x] Reload plugins if another server was selected
- [x] Panel
  - [x] Panel header
    - [x] Action for reloading plugins
  - [x] Table: Show list of plugins
    - [x] Name
    - [x] Description
    - [x] Plugin Version
    - [x] Rust Version (red, if it's non-compatible to the runtime)
    - [x] Plugin API Version (red, if it's non-compatible to the runtime)
    - [x] State and action buttons
      - [x] Action Start (if resolved)
      - [x] Action Stop (if active)
      - [x] Action Uninstall (if resolved)
      - [x] Action Restart (if active)
- [x] Command Center
- [x] Hotkey
- [x] Panel Chip (bottom right)
