### ISSUE TITLE
Panel Servers

### ISSUE THREAD

**Issue by aschaeffer** [aschaeffer/reactive-graph-flow-editor#9]
### Goal

The user can connect to different runtimes and switch between them.

### Tasks

- [ ] List of servers
  - [x] Name (from `servers.toml`)
  - [x] URL (from `servers.toml`)
  - [ ] Reachable (green, if a connection is possible)
  - [ ] Instance Name (from its GraphQL endpoint)
- [x] Select a server as the current server
  - [ ] Reset all global states
- [ ] Read configuration from `servers.toml`
- [ ] Update an entry and save `servers.toml`
- [ ] Create a new entry and save `servers.toml`
